### ISSUE TITLE
作为新手搬砖工的我来给老哥提问题

### ISSUE THREAD

**Issue by 18230149962** [TesterlifeRaymond/doraemon#2]
在下载文件后，我直接将这个包导入到了我的项目中，没有看什么环境，发现缺少一个文件，在和老哥研究后希望老哥把那个文件，push上来帮助我这个弱势群体，谢谢！

**Comment by 18230149962** [comment]
已经解决了，谢谢老哥

**Comment by TesterlifeRaymond** [comment]
互相学习， 都有一个学习的过程， 加油！
