### ISSUE TITLE
没有html模板

### ISSUE THREAD

**Issue by rookie-python** [TesterlifeRaymond/doraemon#3]
我是看着template拉的,可惜并没有

**Comment by TesterlifeRaymond** [comment]
关于template的问题, 可以通过TesterlifeRaymond/BeautifulReport 这个项目 手动同步一次

**Comment by dengying721** [comment]
File "D:\git\doraemon\src\lib\BeautifulReport.py", line 374, in output_report
    with open(template_path, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python36\\Lib\\site-packages/BeautifulReport/template/template'
