### ISSUE TITLE
生成路径有问题

### ISSUE THREAD

**Issue by HakunamatataLeo** [TesterlifeRaymond/doraemon#4]
![image](https://user-images.githubusercontent.com/4550421/48878529-a9dec000-ee42-11e8-8639-15f4b3365989.png)

**Comment by TesterlifeRaymond** [comment]
这里缺少了一个 template 文件,  感谢你的提醒. 可以先通过clone BeautifulReport 这个项目之后放到 python 版本对应的 **site-packages** 路径解决该问题

**Comment by HakunamatataLeo** [comment]
OK
